# install epel repository and remi repository
---
- name: set timezone
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link

- name: yum -y update
  yum: name=* state=latest
  async: 5
  poll: 0

- name: install yum-utils
  yum: name=yum-utils state=present

- name: check if remi-release-7 repository is exist
  stat: path=/etc/yum.repos.d/remi-php72.repo
  register: is_exist

- name: install remi-release-7
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: latest
  when: is_exist.stat.exists == false

- debug: var=is_exist.stat.exists

- name: install EPEL repository
  yum: name=epel-release state=present
  register: is_installed

- debug: var=is_installed

- name: install ius repository
  yum:
    name: https://dl.iuscommunity.org/pub/ius/stable/CentOS/7/x86_64/ius-release-1.0-15.ius.centos7.noarch.rpm
    state: latest
  when: is_installed is success

- name: check if git2u is installed
  yum: list=git2u
  register: is_installed

- debug: var=is_installed

- name: remove old git
  yum: name=git state=absent
  when: is_installed.results|selectattr("yumstate", "match", "installed")|list|length == 0
  register: is_removed

- debug: var=is_removed.results

- name: install the latest version of git
  yum: name=git2u state=latest
  when: is_removed.changed == true or "is_removed.results in 'git is not installed'"
