---
- name: Move MariaDB repository to nginx-server
  template: src=MariaDB.repo.tpl dest=/etc/yum.repos.d/MariaDB.repo

- name: Install MariaDB package
  yum: name={{ item }} state=installed
  with_items:
   - MariaDB-devel
   - MariaDB-client
   - MariaDB-server
   - MySQL-python

- name: Create Mysql configuration file
  template: src=my.cnf.tpl dest=/etc/my.cnf.d/default.cnf
  notify:
  - restart mariadb

- name: Create MariaDB log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql mode=0775

- name: Start MariaDB Service
  service: name=mariadb state=started enabled=yes
