# install epel repository and remi repository
---
- name: set timezone
  file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link

- name: yum -y update
  yum: name=* state=latest
  async: 5
  poll: 0

- name: check remi-release-7
  stat: path=/etc/yum.repos.d/remi-php72.repo
  register: remi_release_7

- name: install remi-release-7
  yum:
    name: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
    state: latest
  when: remi_release_7.stat.exists == false

- name: install EPEL repository
  yum: name=epel-release state=present
